### ISSUE TITLE
ipywidgets slider not working with Solara >v1.17.0

### ISSUE THREAD

**Issue by giswqs** [widgetti/solara#169] opened 2023-06-23 03:49 UTC
The ipywidget slider used to work fine with Solara v1.17.0 and earlier.
![image](https://github.com/widgetti/solara/assets/5016453/abf41874-7638-4480-82bf-f0782c9ef5f2)

However, the slider no longer show up with Solara v1.17.1.  Is there any changes recently that affect ipywdiget slider?
![image](https://github.com/widgetti/solara/assets/5016453/26043ad7-bb98-4fe6-8b90-f3fc7d44d50d)

**Comment by maartenbreddels** [comment] 2023-06-23 15:26
Thank you for reporting!

I can confirm this happened in 1.17.1

**Comment by maartenbreddels** [comment] 2023-06-23 19:11
Fixed in f1fac8a666879139cead66ca44296a75a00c381c and released as 1.17.3 🥳

**Comment by giswqs** [comment] 2023-06-23 19:28
Thank you for the quick fix. One minor issue is that the right end of the slider is a but cut off. See below. It worked perfectly in Solara v0.17.0. as well as in Jupyter notebook (without Solara). Not sure if it is a style issue. 

In Jupyter Notebook
![image](https://github.com/widgetti/solara/assets/5016453/f1d237d5-4598-474a-88ac-ccc1d29ab567)

In Solara web app
![image](https://github.com/widgetti/solara/assets/5016453/052b6a0e-6b91-4b50-aa40-ad45a4f0c6d0)

**Comment by maartenbreddels** [comment] 2023-06-23 19:59
Again, thanks for letting me know!

**Comment by kirimaru-jp** [comment] 2023-08-21 17:14
@maartenbreddels I have the same problem like @giswqs , hence I would like to find out why it happened in order to fix it. However, I did not know how to track the changes you made, e.g. [this one](https://github.com/widgetti/solara/commit/451d10a715a929717adcc7ef97a8a3c5e34caa8d) seems to be incorrect.

Could you please tell me how to find the changes?

**Comment by maartenbreddels** [comment] 2024-01-09 12:35
https://github.com/widgetti/solara/pull/450 might solve this. We'll release this soon (1.25.2 or 1.26.0)

**Closed** 2024-01-16 15:45 UTC
