### ISSUE TITLE
GStreamer Libs not found when used in solara app

### ISSUE THREAD

**Issue by vishalkmr** [widgetti/solara#353] opened 2023-10-29 06:51 UTC
I am trying to make a **gstreamer based app on Solara**. I have already run the streamlit app on gstreamer to verify the gstreamer libraries. 

App containing simple code like
```python
import gi
gi.require_version('Gst', '1.0')
from gi.repository import Gst
import solara
```

give the below error

```
vishkumar@vishkumar-pc:~/code-base/Web-GStreamer$ solara run test.py
Solara server is starting at http://localhost:8765
Traceback (most recent call last):
  File "/usr/local/bin/solara", line 8, in <module>
    sys.exit(main())
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/__main__.py", line 688, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/__main__.py", line 410, in run
    start_server()
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/__main__.py", line 382, in start_server
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/starlette.py", line 48, in <module>
    from . import app as appmod
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/app.py", line 405, in <module>
    apps["__default__"] = AppScript(os.environ.get("SOLARA_APP", "solara.website.pages:Page"))
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/app.py", line 69, in __init__
    app = self._execute()
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/app.py", line 115, in _execute
    with reload.reloader.watch():
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/reload.py", line 230, in watch
    self.watcher.add_file(path)
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/reload.py", line 74, in add_file
    self._watch_file(file)
  File "/home/vishkumar/.local/lib/python3.10/site-packages/solara/server/reload.py", line 77, in _watch_file
    self.mtimes[file] = os.path.getmtime(file)
  File "/usr/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/vishkumar/code-base/Web-GStreamer/<gi.repository.GObject>'
```

Can anyone help me to debug why i am not able to use gstreamer library with solar??

**Comment by maartenbreddels** [comment] 2023-10-30 13:28
I could not reproduce this error, but it should be fixed by https://github.com/widgetti/solara/pull/356

**Comment by maartenbreddels** [comment] 2023-10-30 13:29
Thank you for opening the issue, feel free to join our discord:
[![Discord Shield](https://discordapp.com/api/guilds/1106593685241614489/widget.png?style=banner2)](https://discord.gg/MEpm6sEjdq)

**Closed** 2023-10-30 20:14 UTC
